### ISSUE TITLE
In-game Python script editing

### ISSUE THREAD

**Issue by Nisnow** [HHSProgrammingClub/smash-my-buttons#30]
Putting down some notes for the future

- Separate window
- Syntax highlighting (Michael said he found a thing)
- "Start" button of sorts
- "Save script" and "Load script" buttons
- Some way to display errors (another window?)

**Comment by lgtyqz** [comment]
> Separate window
> Syntax Highlighting
> Start button
> Save/Load Script
The plan now is to just use a text editor or IDLE to write the actual script, and then load it into the program. Post-production, we can add an in-game editor.

> Some way to display errors (another window?)
That might be necessary, since there's no other way to see critical program errors from anywhere else. For now, I think the best option is to start up a command line error list like in the WGE to display program runtime/compile errors.

**Comment by clman94** [comment]
I actually already have the editing and error handling mostly complete. Just need to find a good place to integrate it.

**Comment by Nisnow** [comment]
Wow, nice! Y’all are amazing. Keep up the good work —- looking forward to this.

**Comment by lgtyqz** [comment]
Great work!

When will you push this?

**Comment by clman94** [comment]
It has been pushed.
